export const CALENDAR_ACTIONS = {
  FETCH_CALENDAR: 'FETCH_CALENDAR',
  FETCHED_CALENDAR: 'FETCHED_CALENDAR',
  FAILED_FETCH_CALENDAR: 'FAILED_FETCH_CALENDAR',

  FETCH_CALENDAR_CUSTOM: 'FETCH_CALENDAR_CUSTOM',
  FETCHED_CALENDAR_CUSTOM: 'FETCHED_CALENDAR_CUSTOM',
  FAILED_FETCH_CALENDAR_CUSTOM: 'FAILED_FETCH_CALENDAR_CUSTOM',
};
