export const CONTACTS_ACTIONS = {
  FETCH_CONTACTS: 'FETCH_CONTACTS',
  FETCHED_CONTACTS: 'FETCHED_CONTACTS',
  FAILED_FETCH_CONTACTS: 'FAILED_FETCH_CONTACTS',

  FETCH_PLANT_COMPANIES: 'FETCH_PLANT_COMPANIES',
  FETCHED_PLANT_COMPANIES: 'FETCHED_PLANT_COMPANIES',
  FAILED_FETCH_PLANT_COMPANIES: 'FAILED_FETCH_PLANT_COMPANIES',

  FETCH_DESIGNATIONS: 'FETCH_DESIGNATIONS',
  FETCHED_DESIGNATIONS: 'FETCHED_DESIGNATIONS',
  FAILED_FETCH_DESIGNATIONS: 'FAILED_FETCH_DESIGNATIONS',
};
