export const HOMEPAGE_ACTIONS = {
  FETCH_DESIGNATIONS: 'FETCH_DESIGNATIONS',
  FETCHED_DESIGNATIONS: 'FETCHED_DESIGNATIONS',
  FAILED_FETCH_DESIGNATIONS: 'FAILED_FETCH_DESIGNATIONS',

  FETCH_PLANT_COMPANIES: 'FETCH_PLANT_COMPANIES',
  FETCHED_PLANT_COMPANIES: 'FETCHED_PLANT_COMPANIES',
  FAILED_FETCH_PLANT_COMPANIES: 'FAILED_FETCH_PLANT_COMPANIES',

  FETCH_DEPARTMENTS: 'FETCH_DEPARTMENTS',
  FETCHED_DEPARTMENTS: 'FETCHED_DEPARTMENTS',
  FAILED_FETCH_DEPARTMENTS: 'FAILED_FETCH_DEPARTMENTS',
};
