export const SALES_ACTIONS = {
  FETCH_SALES_LOGS: 'FETCH_SALES_LOGS',
  FETCHED_SALES_LOGS: 'FETCHED_SALES_LOGS',
  FAILED_FETCH_SALES_LOGS: 'FAILED_FETCH_SALES_LOGS',
  UPDATE_SALES_LOGS: 'UPDATE_SALES_LOGS',
};
