import {StyleSheet, Platform} from 'react-native';
import Dimension from '../../Theme/Dimension';
import colors from '../../Theme/Colors';
import {DIFF_DELETE} from 'jest-diff';
const styles = StyleSheet.create({
  NoDataFoundTxt: {
    alignSelf: 'center',
    marginTop: Dimension.margin10,
    color: '#000',
  },
  TopHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headingTxt: {
    fontFamily: Dimension.CustomMediumFont,
    fontSize: Dimension.font18,
    color: colors.FontColor,
  },
  headerWrap: {
    shadowColor: '#000',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
    paddingHorizontal: Dimension.padding15,
    marginBottom: Dimension.margin10,
    paddingVertical:
      Platform.OS == 'ios' ? Dimension.padding15 : Dimension.padding10,
    backgroundColor: '#fff',
  },
  searchWraper: {
    marginTop: Dimension.margin10,
    backgroundColor: '#fff',
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#D3D3D3',
    paddingHorizontal: Dimension.padding10,
    shadowColor: '#000',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
    flexDirection: 'row',
    alignItems: 'center',
    // overflow: 'hidden',
    height: Dimension.height40,

  },
  SearchInputCss: {
    fontSize: Dimension.font12,
    color: colors.FontColor,
    fontFamily: Dimension.CustomRegularFont,
    backgroundColor: '#fff',
    flex: 1,
    marginLeft: 5,
    lineHeight: Dimension.font18,
  },
  seacrhIcon: {
    position: 'absolute',
    top: Dimension.padding12,
    right: Dimension.padding10,
    fontSize: Dimension.font22,
    color: colors.FontColor,
  },
  list: {
    flex: 1,
  },
  contactCon: {
    flex: 1,
    flexDirection: 'row',
    padding: Dimension.padding10,
    borderColor: '#DCE2EA',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 0.5,
    borderTopWidth: 0.5,
    backgroundColor: '#fff',
  },
  imgCon: {},
  placeholder: {
    width: 48,
    height: 48,
    borderRadius: 48,
    overflow: 'hidden',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#D3D3D3',
  },
  contactDat: {
    paddingLeft: 5,
  },
  txt: {
    fontSize: Dimension.font20,
    fontFamily: Dimension.CustomBoldFont,
    color: colors.FontColor,
  },
  name: {
    fontSize: Dimension.font16,
    fontFamily: Dimension.CustomMediumFont,
    color: colors.FontColor,
  },
  phoneNumber: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomRegularFont,
    color: colors.FontColor,
    justifyContent: 'flex-start',
  },
  arrowBtn: {
    position: 'absolute',
    right: 20,
    width: 20,
    height: 20,
    top: 20,
  },
  datetxt: {
    marginLeft: Dimension.margin10,
  },
  BtnWrap: {
    borderWidth: 1,
    borderColor: '#1568E5',
    borderRadius: 50,
    flexDirection: 'row',
    alignSelf: 'flex-start',
    paddingHorizontal: Dimension.padding5,
    paddingVertical: 2,
  },
  TopBtn: {
    paddingHorizontal: Dimension.padding20,
    paddingVertical: Dimension.padding6,
    backgroundColor: '#fff',
    borderRadius: 50,
  },
  BtnTxt: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomMediumFont,
    color: '#1568E5',
  },
  ActiveTopBtn: {
    paddingHorizontal: Dimension.padding20,
    paddingVertical: Dimension.padding6,
    backgroundColor: '#1568E5',
    borderRadius: 50,
  },
  ActiveBtnTxt: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomMediumFont,
    color: '#fff',
  },
  filterbtn: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: colors.CtaColor,
    borderRadius: 50,
    paddingHorizontal: Dimension.padding20,
    // paddingVertical: Dimension.padding5,
    alignSelf: 'center',
    marginBottom: 12,
  },
  filtertxt: {
    fontFamily: Dimension.CustomMediumFont,
    fontSize: Dimension.font14,
    color: colors.CtaColor,
    marginLeft: Dimension.margin6,
    marginTop: 1,
  },
});

export default styles;
